.TH 42SH

.SH NAME
.P
42sh

.SH SYNOPSIS
.P
\fB42sh\fR [\fIOPTIONS\fR] [\fIFILE\fR]

.SH DESCRIPTION
.P
42sh is an sh-compatible command language interpreter that executes commands
read from the standard input or from a file.

.SH OPTIONS
.P

42sh interprets the following options when it is invoked:

--version Show version information on this version and exist successfully.

.SH SEE ALSO
.P
http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html

.SH AUTHORS
.P

\- Tristan MARTIN
.P
\- Othman SEQQAT
.P
\- Leo TORDJMAN
.P
\- Jean-Louis UNG
